### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by SandedShoes** [SandedShoes/Weeping-Angels#30]
- [x] Make teleporter code cleaner
- [ ] Make Angel arms grab players legs 
- [ ] Finish and actually come up with a concept for angel sickness
- [x] Fix the blockstate for the cg block 
- [x] Look into better sounds
- [ ] Add catacomb generation back
- [x] Fix some deprecated methods
- [ ] Re-write the angel painting entity, that thing buggy afff  

Things to put off for now:
- [x] Angel on Angel quantum locking

**Comment by SandedShoes** [comment]
I have other plans
